Feature 130 settings variable name
Metatavu/megasense-data-portal-api pull request #132
Opened 2021-11-22 20:02 UTC by Chi-Chu319

resolves #130

2021-11-23 12:35 UTC, Daniilmass approved these changes

2021-11-23 14:05 UTC, kaeline requested changes

2021-11-23 14:07 UTC, kaeline commented on src/main/kotlin/fi/metatavu/megasense/dataportal/api/V1ApiImpl.kt
> +                    thresholdRequestParameter = payload.requestParameters.thresholdRequestParameter,
Should this data come from endpoint?

2021-11-23 14:09 UTC, kaeline commented on src/main/kotlin/fi/metatavu/megasense/dataportal/api/V1ApiImpl.kt
> +                    thresholdRequestParameter = payload.requestParameters.thresholdRequestParameter,
Should we keep the create pollutant endpoint if all the data comes from settings.json instead?

2021-11-23 14:13 UTC, Chi-Chu319 commented on src/main/kotlin/fi/metatavu/megasense/dataportal/api/V1ApiImpl.kt
> +                    thresholdRequestParameter = payload.requestParameters.thresholdRequestParameter,
They shouldn't but thresholdRequestParameter, penaltyRequestParameter and variableName are all not nullable

2021-11-23 14:46 UTC, kaeline commented on src/main/resources/db/changeLog.xml
> +            <column name="penaltyRequestParameter" type="varchar(100)" defaultValue="harmful_micro_particles_PM2_5_threshold">
it is not nullable but it can be empty. maybe set default value as empty string to avoid confusion? Same for variableName and thresholdRequestParameter

2021-11-23 20:05 UTC, kaeline commented on src/main/kotlin/fi/metatavu/megasense/dataportal/airquality/PollutantController.kt
> +                    logger.info("updated pollutant ${indexVariable.name}")
```suggestion
                    logger.info("Updated pollutant ${indexVariable.name}")
```

2021-11-24 11:50 UTC, kaeline commented on src/main/kotlin/fi/metatavu/megasense/dataportal/airquality/PollutantController.kt
> +    private fun updatePollutantOnStart(
```suggestion
    private fun updatePollutant(
```
Consider overloading method instead of creating one with separate name?

2021-11-24 11:51 UTC, kaeline approved these changes

2021-11-24 11:54 UTC, kaeline commented on src/main/kotlin/fi/metatavu/megasense/dataportal/airquality/PollutantController.kt
> +import fi.metatavu.megasense.dataportal.configuration_parsing.GenericFileConfiguration
Rearrange order of methods to have the private ones in the very end and sort public methods in order: list, create, find, update, delete

2021-11-24 12:17 UTC, Chi-Chu319 commented on src/main/kotlin/fi/metatavu/megasense/dataportal/airquality/PollutantController.kt
> +    private fun updatePollutantOnStart(
very good point... will do that

2021-11-24 16:11 UTC, merged